INSERT INTO questions (
        quizId,
        attachment,
        body,
        option_a,
        option_b,
        option_c,
        option_d,
        option_e,
        attachment_a,
        attachment_b,
        attachment_c,
        attachment_d,
        attachment_e,
        answer
    )
VALUES (
        1,
        '',
        'Contoh Pertanyaan 1',
        'Opsi A',
        'Opsi B',
        'Opsi C',
        'Opsi D',
        'Opsi E',
        'attachment_a',
        'attachment_b',
        'attachment_c',
        'attachment_d',
        'attachment_e',
        'a'
    ),
    (
        1,
        '',
        'Contoh Pertanyaan 2',
        'Opsi A',
        'Opsi B',
        'Opsi C',
        'Opsi D',
        'Opsi E',
        'attachment_a',
        'attachment_b',
        'attachment_c',
        'attachment_d',
        'attachment_e',
        'a'
    ),
    (
        1,
        '',
        'Contoh Pertanyaan 3',
        'Opsi A',
        'Opsi B',
        'Opsi C',
        'Opsi D',
        'Opsi E',
        'attachment_a',
        'attachment_b',
        'attachment_c',
        'attachment_d',
        'attachment_e',
        'a'
    ),
    (
        1,
        '',
        'Contoh Pertanyaan 4',
        'Opsi A',
        'Opsi B',
        'Opsi C',
        'Opsi D',
        'Opsi E',
        'attachment_a',
        'attachment_b',
        'attachment_c',
        'attachment_d',
        'attachment_e',
        'a'
    );